apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | b64enc | quote }}
  mysql-database: {{ .Values.secrets.mysqlDatabase | b64enc | quote }}
  mysql-user: {{ .Values.secrets.mysqlUser | b64enc | quote }}
  mysql-password: {{ .Values.secrets.mysqlPassword | b64enc | quote }}